export const TEST_DATA = {
    api_stat: {
        highlights: [
            { name: "pentaKills", value: 10, category: "Combat" },
            { name: "largestCriticalStrike", value: 2500, category: "Combat" },
            { name: "longestTimeSpentLiving", value: 1200, category: "Gameplay" },
        ],
        stats: [
            { name: 'largestKillingSpree', value: 0, category: 'combat' },
            { name: 'largestMultiKill', value: 1, category: 'combat' },
            { name: 'longestTimeSpentLiving', value: 692, category: 'gameplay' },
            { name: 'magicDamageDealt', value: 4200, category: 'combat' },
            { name: 'magicDamageDealtToChampions', value: 666, category: 'combat' },
            { name: 'magicDamageTaken', value: 5370, category: 'combat' },
            { name: 'neutralMinionsKilled', value: 2, category: 'gameplay' },
            { name: 'nexusKills', value: 0, category: 'objectives' },
            { name: 'nexusLost', value: 0, category: 'objectives' },
            { name: 'nexusTakedowns', value: 1, category: 'objectives' },
            { name: 'objectivesStolen', value: 0, category: 'support' }
        ]
    }
}


export const champions = [
  "Aatrox",
  "Ahri",
  "Akali",
  "Akshan",
  "Alistar",
  "Ambessa",
  "Amumu",
  "Anivia",
  "Annie",
  "Aphelios",
  "Ashe",
  "AurelionSol",
  "Aurora",
  "Azir",
  "Bard",
  "BelVeth",
  "Blitzcrank",
  "Brand",
  "Braum",
  "Briar",
  "Caitlyn",
  "Camille",
  "Cassiopeia",
  "ChoGath",
  "Corki",
  "Darius",
  "Diana",
  "DrMundo",
  "Draven",
  "Ekko",
  "Elise",
  "Evelynn",
  "Ezreal",
  "Fiddlesticks",
  "Fiora",
  "Fizz",
  "Galio",
  "Gangplank",
  "Garen",
  "Gnar",
  "Gragas",
  "Graves",
  "Gwen",
  "Hecarim",
  "Heimerdinger",
  "Hwei",
  "Illaoi",
  "Irelia",
  "Ivern",
  "Janna",
  "JarvanIV",
  "Jax",
  "Jayce",
  "Jhin",
  "Jinx",
  "KSante",
  "Kaisa",
  "Kalista",
  "Karma",
  "Karthus"
];